//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pojarov_DEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class podzharow_DEMO
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img_path { get; set; }
        public string description { get; set; }
        public string manufacturer { get; set; }
        public Nullable<double> prise { get; set; }
        public Nullable<double> descount { get; set; }
    }
}
